print("Labdien! Lūdzu izprintē savu vārdu un uzvārdu jaunā rindā, izmantojot Python kodu")
print("Mani sauc Artūrs Ausējs")
print("Artūrs Ausējs")
print("Elvita Petrauska")
print("Luīze Vītoliņa")
print("Tomass Girdenis")
