print("Labdien! Lūdzu izprintē savu vārdu un uzvārdu jaunā rindā, izmantojot Python kodu")
print("Mani sauc Artūrs Ausējs")
print("Artūrs Ausējs")
print("Elvita Petrauska")
print("Luīze Vītoliņa")
print("Patrīcija Špakovska")
print("Luīze Vītoliņa")
print("Martins Vikmanis")
print("Anna Mišela Tunika")
print('Estere Ilze Ozolina')
print("Martins Vikmanis")